### ISSUE TITLE
Crash on Load with Spectrite 1.44 for 1.12

### ISSUE THREAD

**Issue by jsaggers** [Samuel-Harbord/SpectriteMod#14]
[crash-2017-08-13_17.21.50-client.txt](https://github.com/Samuel-Harbord/Spectrite/files/1220329/crash-2017-08-13_17.21.50-client.txt)
I have tried a few different versions of forge, I also created an instance of minecraft with just the spectrite mod and it still crashes.

**Comment by Flashfyre** [comment]
Oh boy. Can't believe I forgot about that. Try 1.4.5.
