### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by 0dikpah** [Samuel-Harbord/SpectriteMod#16]
Minecraft 1.12
spectrite 1.4.4-1.12
forge1.12-14.21.1.2443
[crash-2017-08-13_20.34.54-client.txt](https://github.com/Samuel-Harbord/Spectrite/files/1220669/crash-2017-08-13_20.34.54-client.txt)

**Comment by Flashfyre** [comment]
Fixed in 1.4.5
