### ISSUE TITLE
Crash in Debug World

### ISSUE THREAD

**Issue by mezz** [Samuel-Harbord/SpectriteMod#20]
Minecraft has a Debug world mode, https://minecraft.gamepedia.com/Debug_mode

Spectite crashes when you enter this world:
https://gist.github.com/mezz/495bf74c531aed0c184090dfc194b152

**Comment by Flashfyre** [comment]
First I've heard of this. Will fix for next version. For the time being, you can disable Spectrite Skull generation in the config.

**Comment by Flashfyre** [comment]
I fixed it by checking the make sure generateStructures is enabled in a created world which i false for debug worlds (it should have been doing this in the first place but I overlooked it). This will take effect as of 1.5.0.

**Comment by mezz** [comment]
Thanks!
