### ISSUE TITLE
Spectrite apple 

### ISSUE THREAD

**Issue by ghost** [Samuel-Harbord/SpectriteMod#22]
You can add a spectrite apple, create with notch apple and spectrite

**Comment by Flashfyre** [comment]
What do you suppose it would provide?

**Comment by ghost** [comment]
When the spectrite apple was eat, the player get lots of good effects like a notch apple but for a long time and with others effects (jump boost, speed X...).

**Comment by Flashfyre** [comment]
I already have a plan to provide effects through different Spectrite Orbs in the next update, and they are passive effects. The mod will no longer be providing Vanilla effects either and will instead provide custom ones. There are currently no edible Spectrite items either (it is a mineral after all). Sorry but I'm going to have to pass on this one.
