### ISSUE TITLE
dungeon

### ISSUE THREAD

**Issue by ghost** [Samuel-Harbord/SpectriteMod#28]
After setting this to false to not Generate Spectrite Dungeon, it still gens them all over the map when I have it disabled.

    spectritedungeon {
        B:generateSpectriteDungeon=false

        # Valid values:
        # NONE
        # HIGH_TIER_ONLY
        # MEDIUM_AND_HIGH_TIER
        # ALL_TIERS
        S:spectriteDungeonChestMode=NONE

**Comment by Flashfyre** [comment]
"All over the map" eh? Are you sure you're not confusing this with the Spectrite Skull structure? There's only one Spectrite Dungeon per map.
