### ISSUE TITLE
Spectrite crystal isn't a placeable block?

### ISSUE THREAD

**Issue by chaosblad3** [Samuel-Harbord/SpectriteMod#32]
I crafted some spectrite crystals but when I try to place one by right clicking it on a block nothing happens...

I even tried seeing if I could use /setblock but when I get to the `<block>` part of the command there is no mention of the crystal in the [tab] complete list: https://i.imgur.com/PQkJTLW.png

Version 1.7.1

**Comment by Flashfyre** [comment]
It's like the regular Ender Crystal, you can only place it on bedrock or obsidian.
