### ISSUE TITLE
Spectrite Dungeon not spawning in flat world

### ISSUE THREAD

**Issue by Tom25W** [Samuel-Harbord/SpectriteMod#39]
The Spectrite Dungeon is not generated once a flatland world is created. Crafting a Spectrite Compass will rotate its needle in every direction at random - just like a regular compass in the nether.

**Comment by Flashfyre** [comment]
This is intentional. There is no way that there could be one because it is a structure that is intended to be hidden underground and the world is not deep enough for it so it's disabled on this type.
