### ISSUE TITLE
Nether Skull Missing Spawners

### ISSUE THREAD

**Issue by rongineering** [Samuel-Harbord/SpectriteMod#40]
Playing with the latest version on 1.12.2 in a custom modpack. I have found 2 skulls in the nether so far and both of them only have the blaze spawner in them, all the others are missing. Have not found one in the overworld yet to know if they are messed up there as well.

**Comment by Flashfyre** [comment]
This is correct behaviour. Previously, the skeleton spawners were a way to infinitely farm Spectrite items which were not intended to be acquired so easily. Now mobs are added alongside the generation of the structure and are altered so they don't despawn (unless of course you kill them). If you are not seeing any mobs at all other than blazes then there is a problem, but if you did see the skeletons then it's working as intended.

**Comment by rongineering** [comment]
Fair enough. It is working as intended then. Blaze spawner and mobs that didn't respawn after being killed were present in both. 
I was just reading through all the descriptions on the main page and saw that there were supposed to be 5 spawners and was concerned that my world was broken somehow.

**Comment by Flashfyre** [comment]
It seems I forgot to update the readme after the change then. Thank you for that.
